language: php

php: 
  - 7.3

before_script:
  - travis_retry composer self-update
  - travis_retry composer install
  - cp .env.example .env
  - php artisan key:generate

script:
  - vendor/bin/phpunit